### ISSUE TITLE
Feature Request:  slots

### ISSUE THREAD

**Issue by sslupsky** [pgilfernandez/FreeCAD_Fastener_holes#2]
Would it be possible to add a "slot" type to the hole macro?  My use case is a pulley tensioner where the bolt needs to be in a slot rather than a hole so it is free to slide in one dimension.  The nut groove could be extruded normal, reverse normal or symmetrical normal to a plane coplanar to the axis of the bolt.

**Comment by pgilfernandez** [comment]
Umm, I think I understand you but, would you mind sharing a picture so that I can visually get it?

Thanks

**Comment by sslupsky** [comment]
Certainly.  Here are a couple screen shots that illustrate what I am talking about.  In this example, I sketched a couple hexagons centred around the screw holes, connected them along their flats and then pocketed them.

![Screen Shot 2020-02-11 at 8 18 05 AM](https://user-images.githubusercontent.com/16888734/74249930-227ba780-4ca7-11ea-9744-609c35719fc5.png)
![Screen Shot 2020-02-11 at 8 18 17 AM](https://user-images.githubusercontent.com/16888734/74249940-25769800-4ca7-11ea-89d5-ffc70eb82df9.png)

**Comment by pgilfernandez** [comment]
Yes, I get it now.
I guess you would like this feature to be able as an option for each hole I have already listed and with an option to set the width, doesn't it?

**Comment by pgilfernandez** [comment]
I have just updated the macro with support for "slots".

You can try it out ;)
